vich_uploader:
    db_driver: orm

    mappings:
        documents:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'

        produit_attachements:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
        produit_thumbnail:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
